@port=3001

### CATEGORIES ###

GET http://localhost:{{port}}/categories

###
POST http://localhost:{{port}}/categories
Content-Type: application/json

{
    "name": "CAFÉS",
    "image_url": "https://img77.uenicdn.com/image/upload/v1571152283/service_images/shutterstock_792219154.jpg",
    "day_shift": "DAY"
}

###
@category_id=1

PUT http://localhost:{{port}}/categories/{{category_id}}
Content-Type: application/json

{
    "name": "Doces",
    "image_url": "https://img77.uenicdn.com/image/upload/v1571152283/service_images/shutterstock_792219154.jpg",
    "day_shift": "ALL"
}

###
DELETE http://localhost:{{port}}/categories/{{category_id}}


@name=smash da casa

@product_id=1

### PRODUCTS ###

GET http://localhost:{{port}}/products

###
GET http://localhost:{{port}}/products?category_id={{category_id}}

###
GET http://localhost:{{port}}/products?name={{name}}

###
GET http://localhost:{{port}}/products?category_id={{category_id}}&name={{name}}

###
GET http://localhost:{{port}}/products/1

###
POST http://localhost:{{port}}/products/
Content-Type: application/json

{
    "name": "Cappuccino",
    "price": 14.90,
    "description": "Café",
    "image_url": "https://t2.gstatic.com/licensed-image?q=tbn:ANd9GcRRto3IlY56MlAIOAvXHvPEVxBDVzG1uz1zULEBYdJ-I4Aa-xOyPEVvv7fmIjLnxaOz",
    "day_shift": "DAY",
    "category_id": 9
}

###
PUT http://localhost:{{port}}/products/{{product_id}}
Content-Type: application/json

{
    "name": "Mojito",
    "price": 18.90,
    "description": "Drink de limão",
    "image_url": "https://t2.gstatic.com/licensed-image?q=tbn:ANd9GcRRto3IlY56MlAIOAvXHvPEVxBDVzG1uz1zULEBYdJ-I4Aa-xOyPEVvv7fmIjLnxaOz",
    "day_shift": "NIGHT",
    "category_id": 8
}

###
DELETE http://localhost:{{port}}/products/4



### MENU ###

GET http://localhost:{{port}}/menu
